spring:
  application:
    name: book

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
  profiles:
    active: dev
    include: secret

  output:
    ansi:
      enabled: always


server:
  port: 8080



logging:
  output:
    ansi:
      enabled: always