# === MySQL ?? ===
spring.datasource.url=jdbc:mysql://localhost:3306/uswbook
spring.datasource.username=testuser
spring.datasource.password=1234

# === JPA ?? ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# === Redis ?? ===
spring.data.redis.host=localhost
spring.data.redis.port=6379

# === JWT ?? ===
jwt.secret=my-super-secret-jwt-key-that-is-long-enough
jwt.access-expiration=900  # 15?
jwt.refresh-expiration=604800  # 7?

# === ???(Gmail SMTP) ?? ===
spring.mail.host=smtp.gmail.com  
spring.mail.port=587  
email.id=uswbookverify@gmail.com  # 
spring.email.password=mgjv mdwd tpdr fwzp     # 
spring.mail.properties.mail.smtp.auth=true  
spring.mail.properties.mail.smtp.starttls.enable=true


#spring:
#datasource:
#url: jdbc:mysql://localhost:3306/uswbook
#username: testuser
#password: 1234
#
#jpa:
#hibernate:
#ddl-auto: update
#properties:
#hibernate:
#dialect: org.hibernate.dialect.MySQL8Dialect
#show-sql: true
#
#data:
#redis:
#host: localhost
#port: 6379
#
#mail:
#host: smtp.gmail.com
#port: 587
#username: your-email@gmail.com # ??? ?? ??? ?? ??
#password: your-app-password     # ??? ?? ? ???? ??
#properties:
#mail:
#smtp:
#auth: true
#starttls:
#enable: true
#
#jwt:
#secret: my-super-secret-jwt-key-that-is-long-enough
#access-expiration: 900       # 15?
#refresh-expiration: 604800   # 7?
