spring:
  application:
    name: book
  profiles:
    active: dev
    include: secret
  output:
    ansi:
      enabled: always

server:
  port: 8080

logging:
  output:
    ansi:
      enabled: always
