# application-stg.yml
spring:
  data:
    redis:
      host: redis_1
      port: 6379
      password: ${custom.stg.redis.password}
  datasource:
    url: jdbc:mysql://mysql_1:3306/subook_stg?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: subook_stg_user
    password: ${custom.stg.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

custom:
  site:
    domain: stg.subook.shop
    backUrl: https://stg.subook.shop
    frontUrl:
