spring:
  application:
    name: book

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

  profiles:
    include: secret
    active: dev

  output:
    ansi:
      enabled: always

  mail:
    host: smtp.gmail.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true