spring:
  mail:
    username:
    password:
custom:
  jwt:
    secret-key:
  prod:
    db:
      password:
    redis:
      password:
  aws:
    s3:
      bucket:
    credentials:
      access-key:
      secret-key: